# Generated by Django 6.0.3 on 2026-03-08 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mock_Api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="requestapi",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mockapi",
            name="endpoint_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="mockapi",
            name="status_code",
            field=models.IntegerField(
                verbose_name=[
                    (200, "200 OK"),
                    (201, "201 Created"),
                    (204, "204 No Content"),
                    (400, "400 Bad Request"),
                    (401, "401 Unauthorized"),
                    (403, "403 Forbidden"),
                    (404, "404 Not Found"),
                    (500, "500 Internal Server Error"),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mockapi",
            unique_together={("user", "endpoint_id", "method")},
        ),
    ]
