# Generated by Django 6.0.2 on 2026-03-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mock_Api", "0002_requestapi_user_alter_mockapi_endpoint_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestapi",
            name="status",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
